#!/bin/sh

# This shel script stops and deletes an already existing pde with 
# a given name

if [ "$#" -ne 1 ]; then
  echo "(pde) delete requires then name of the podman dev env"
  exit -1
fi

podman container rm $1
